apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: workflow-controller
value: 1000000
globalDefault: false
description: "Priority class for the Argo-based workflow controller pods, required by Kubeflow Pipelines."