apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-meta
  namespace: argocd
spec:
  project: default
  source:
    path: components/kubeflow
    repoURL: 'https://github.com/ardemk606/mlops-platform-config.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true