apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeflow-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ .Values.kubeflow.repoURL }}
    targetRevision: {{ .Values.kubeflow.version }}
    path: manifests/kustomize/cluster-scoped-resources
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kubeflow
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]